### PR TITLE
some minor scss rules added

### PR DESCRIPTION
**Pull request by REPTILEHAUS**
Got a start on the conversion to SASS for you but theres far too many stylus files for me to take this on as a pro bono job at the moment... I was hoping I could write a script and have it do most of the work for me but sadly it was also consuming too much time and failed.

### CODE REVIEW

**Comment by butlerx** [comment]
thanks for the start if you want i could make a branch to have this merge in to

**Comment by REPTILEHAUS** [comment]
Yeah sure :) sorry, I use git quite a lot but not for collaborating with others so Im not really all that up on the lingo - I just work alone and have my own private git server.  Whats entailed, do I still push to my fork but just to a different branch when pushing ? and then submit a new pull req ?

**Comment by SeanHealy33** [comment]
Yep 🐰 
You can merge stuff from your `origin` fork to the master branch on `upstream`
https://felipec.wordpress.com/2014/05/11/git-triangular-workflows/

**Comment by butlerx** [comment]
ive switched the base there for you if you want me to merge it

**Comment by REPTILEHAUS** [comment]
You may as well be speaking chinese ;)
Basically I fired this lot off, again totally new to using git for collaboration:
git checkout -b scss-migration
git merge master scss-migration

Tried to push but it says its all up to date, to be expected I guess, so I figure I should be using some other command ?

**Comment by butlerx** [comment]
youre fine ive done all the work that needs to be done to merge it to a different branch here

**Comment by REPTILEHAUS** [comment]
Just out of interest how do you do that ?

**Comment by butlerx** [comment]
in the pull request you can modify the branch you want the pull request to go too, the base branch, i changed it from my end

**Comment by SeanHealy33** [comment]
If you click edit on the PR you can specify the branch you want to merge into with the drop down 😄 

screen shot 2016-10-04 at 16 37 43

**Comment by REPTILEHAUS** [comment]
Ah very good, Im a learnin'  :D

**Pull request merged**
